// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMYwvRKkIRjxcRE65FthGaRF60f7vGvD4',
    appId: '1:584106183951:web:5ff5f39149f2e98078827a',
    messagingSenderId: '584106183951',
    projectId: 'chat-app-4831c',
    authDomain: 'chat-app-4831c.firebaseapp.com',
    storageBucket: 'chat-app-4831c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzq62gJ-qCUS_jd-z8MpieEQcdYawdk0U',
    appId: '1:584106183951:android:48adffd6c8edb7f578827a',
    messagingSenderId: '584106183951',
    projectId: 'chat-app-4831c',
    storageBucket: 'chat-app-4831c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUdxt1zwAEVdTGKJVrIdKbXF174hvUkIE',
    appId: '1:584106183951:ios:3984d6be2a1b912278827a',
    messagingSenderId: '584106183951',
    projectId: 'chat-app-4831c',
    storageBucket: 'chat-app-4831c.appspot.com',
    iosBundleId: 'com.example.chatMessangerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUdxt1zwAEVdTGKJVrIdKbXF174hvUkIE',
    appId: '1:584106183951:ios:55c00fdaa9a5080a78827a',
    messagingSenderId: '584106183951',
    projectId: 'chat-app-4831c',
    storageBucket: 'chat-app-4831c.appspot.com',
    iosBundleId: 'com.example.chatMessangerApp.RunnerTests',
  );
}
