// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqmsMutS8R6Bom0i5Lc7XRK3wog9DfPAk',
    appId: '1:1049750367111:web:aba57c90dc2b3d88bcc122',
    messagingSenderId: '1049750367111',
    projectId: 'video-call-zegocloud',
    authDomain: 'video-call-zegocloud.firebaseapp.com',
    storageBucket: 'video-call-zegocloud.appspot.com',
    measurementId: 'G-DJKYNSRT0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwn1Cd1B4AlJSAljr95rcSVM9vmX4sJC0',
    appId: '1:1049750367111:android:a4e3f98f88c9f73dbcc122',
    messagingSenderId: '1049750367111',
    projectId: 'video-call-zegocloud',
    storageBucket: 'video-call-zegocloud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZp4_bIExMiR6GMv1Y8uXdsfKNvGDZf4U',
    appId: '1:1049750367111:ios:f58544ef91d6e795bcc122',
    messagingSenderId: '1049750367111',
    projectId: 'video-call-zegocloud',
    storageBucket: 'video-call-zegocloud.appspot.com',
    iosClientId: '1049750367111-307hia3pucd2tjhibofa9qr3cq922712.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZp4_bIExMiR6GMv1Y8uXdsfKNvGDZf4U',
    appId: '1:1049750367111:ios:f58544ef91d6e795bcc122',
    messagingSenderId: '1049750367111',
    projectId: 'video-call-zegocloud',
    storageBucket: 'video-call-zegocloud.appspot.com',
    iosClientId: '1049750367111-307hia3pucd2tjhibofa9qr3cq922712.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqmsMutS8R6Bom0i5Lc7XRK3wog9DfPAk',
    appId: '1:1049750367111:web:a33e67e998de7ac3bcc122',
    messagingSenderId: '1049750367111',
    projectId: 'video-call-zegocloud',
    authDomain: 'video-call-zegocloud.firebaseapp.com',
    storageBucket: 'video-call-zegocloud.appspot.com',
    measurementId: 'G-63MLXSFJBH',
  );
}
